"""add user_id to social_generations

Revision ID: 663ed1260693
Revises: 0001
Create Date: 2026-08-31 14:25:23.521570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '663ed1260693'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_generations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_content', sa.Text(), nullable=False),
    sa.Column('platform', sa.Enum('instagram', 'linkedin', 'x', 'facebook', name='platform_type'), nullable=False),
    sa.Column('image_query', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('image_approved', sa.Boolean(), nullable=False),
    sa.Column('hashtags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hashtags_approved', sa.Boolean(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('caption_approved', sa.Boolean(), nullable=False),
    sa.Column('char_limit', sa.Integer(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'ready', 'saved', name='generation_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_generations_user_id'), 'social_generations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_generations_user_id'), table_name='social_generations')
    op.drop_table('social_generations')
    # ### end Alembic commands ###
